version: "3.6"

services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
        - LOG_LEVEL=debug
    environment:
      DOMAIN: "0.0.0.0"
      HOST: "0.0.0.0"
      REDIS_URL: "sessions_store"
    expose:
      - "3000"
    command: ["npm", "run", "start"]
    volumes:
      - "./:/app"
    secrets:
      - jwt_secret # used to sign jwt tokens
      - db_url # Secret to keep username/password out of repo/image
      - session_secret # used to sign session cookies

  reverse_proxy:
    image: baremaximum/nginx-reverse-proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy/certs:/etc/nginx/certs
    ports:
      - "3001:443"

  mongodb:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    environment: { AUTH: "no" }

  sessions_store:
    image: "redis:latest"
    ports:
      - "6379:6379"

secrets:
  jwt_secret:
    file: ./jwt_secret.txt
  db_url:
    file: ./db_url.txt # Point to mongodb service name defined here
  session_secret:
    file: ./session_secret.txt
