version: "3.7"

services:
  api:
    image: "usersessions:latest"
    build: "."
    environment:
      NODE_ENV: "development"
      LOG_LEVEL: "debug"
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    volumes:
      - "./dist:./"

    secrets:
      - jwt_secret # used to sign jwt tokens

  mongodb:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    environment: { AUTH: "no" }

  sessions_store:
    image: "redis:latest"

secrets:
  jwt_secret:
    file: .//jwt_secret.txt
  db_url:
    file: db_url.txt # Point to mongodb service name defined here
