version: "3.6"

services:
  api:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      LOG_LEVEL: "debug"
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
    volumes:
      - "./dist/:/app/dist"

    secrets:
      - jwt_secret # used to sign jwt tokens
      - db_url # Secret to keep username/password out of repo/image

  mongodb:
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    environment: { AUTH: "no" }

  sessions_store:
    image: "redis:latest"

secrets:
  jwt_secret:
    file: ./jwt_secret.txt
  db_url:
    file: ./db_url.txt # Point to mongodb service name defined here
